# Generated by Django 5.1.3 on 2025-04-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_userpasswordstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPasswordState',
        ),
    ]
