# Generated by Django 5.1.3 on 2025-04-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
