# Generated by Django 5.1.3 on 2025-02-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.recipientgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.sender')),
            ],
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
