# Generated by Django 5.1.3 on 2025-05-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='first_name',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='last_name',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='position',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True),
        ),
    ]
