# Generated by Django 5.1.3 on 2025-02-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_message_delete_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
