# Generated by Django 5.1.3 on 2025-02-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_clicklog_credentiallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='campaign_name',
            field=models.CharField(default='Unnamed Campaign', max_length=255),
        ),
    ]
