# Generated by Django 5.1.3 on 2025-02-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_message_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(to='campaigns.recipient'),
        ),
    ]
