# Generated by Django 5.1.3 on 2025-05-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_recipientgroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientgroup',
            name='user',
        ),
    ]
