# Generated by Django 5.1.3 on 2025-02-28 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_remove_message_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.message'),
            preserve_default=False,
        ),
    ]
