# Generated by Django 5.1.3 on 2025-02-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_clicklog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicklog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.message'),
        ),
    ]
