# Generated by Django 5.1.3 on 2025-05-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_clicklog_user_credentiallog_user_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicklog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='credentiallog',
            name='user',
        ),
    ]
