# Generated by Django 5.1.3 on 2025-03-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AddField(
            model_name='clicklog',
            name='platform',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
