# Generated by Django 5.1.3 on 2025-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_credentiallog_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentiallog',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
