# Generated by Django 5.1.3 on 2025-03-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_alter_credentiallog_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='host',
            field=models.URLField(blank=True, null=True),
        ),
    ]
